name: Terraform CI

on:
  push:
    paths:
      - 'environments/dev/**'
  pull_request:

jobs:
  terraform:
    name: 'Terraform Validate & Plan'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create terraform.tfvars
        run: |
          cat <<EOF > terraform.tfvars
          subscription_id   = "${{ secrets.SUBSCRIPTION_ID }}"
          tenant_id         = "${{ secrets.TENANT_ID }}"
          client_id         = "${{ secrets.CLIENT_ID }}"
          client_secret     = "${{ secrets.CLIENT_SECRET }}"
          application_name  = "${{ secrets.TFVAR_APPLICATION_NAME }}"
          environment_name  = "${{ secrets.TFVAR_ENVIRONMENT_NAME }}"
          primary_location  = "${{ secrets.TFVAR_PRIMARY_LOCATION }}"
          tags = {
            owner = "${{ secrets.TFVAR_TAG_OWNER }}"
            env   = "${{ secrets.TFVAR_TAG_ENV }}"
          }
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -input=false
